apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: vm-ubuntu-sur-utm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mon-api-service
                port:
                  number: 8001