version: '3.7'

services:
  mon_api:
    build: ./API
    ports:
      - 8001:8000
    environment:
      - MYSQL_URL=ma-bdd-service
      - MYSQL_PASSWORD=mdp
    depends_on:
      - ma-bdd-service

  ma-bdd-service:
    build: ./BDD
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: bdd_test
      MYSQL_PASSWORD: mdp
    ports:
      - "3306:3306"
    volumes:
      - ma_bdd_data:/var/lib/mysql

volumes:
  ma_bdd_data: