apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ma-bdd-statefulset
  labels:
    app: ma_bdd
spec:
  serviceName: ma-bdd
  replicas: 3
  selector:
    matchLabels:
      app: ma_bdd
  template:
    metadata:
      labels:
        app: ma_bdd
    spec:
      containers:
        - name: ma-bdd-conteneur
          image: dockersebc/datascientest-exam-kubernetes-ma-bdd:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: ma-bdd-data
              mountPath: /var/lib/mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mdp"
          - name: MYSQL_DATABASE
            value: "bdd_test"
          - name: MYSQL_PASSWORD
            value: "mdp"
  volumeClaimTemplates:
    - metadata:
        name: ma-bdd-data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
