apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-api-deployment
  labels:
    app: mon_api
spec:
  selector:
    matchLabels:
      app: mon_api
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mon_api
    spec:
      containers:
        - name: mon-api-conteneurs
          image: dockersebc/datascientest-exam-kubernetes-1:latest
          ports:
            - containerPort: 8000 # Port exposer par le conteneur Docker
          envFrom:
            - secretRef: 
                name: mon-api-secret
      restartPolicy: Always  # Politique de redémarrage
